### ISSUE TITLE
App closes when clicking on transactions tab

### ISSUE THREAD

**Issue by mygitaccount420** [Nexusoft/nexus-mobile#27]
App crashes when clicking on transactions, and sometimes get "invalid credentials" when trying to log back in.
Cant recive transactions either. 

[0.log](https://github.com/Nexusoft/nexus-mobile/files/11053777/0.log)

**Comment by mygitaccount420** [comment]
Problem still presist in v.0.9.3-3
Unable to claim transactions and wallet crashes when clicking on transacions.
Before it crashes immideatly, but now it crahes after loading for 10-20 seconds
when clicking on transactions tab.

**Comment by KenCorma** [comment]
Do me a favor, there was an issue on 0.9.3 which was suppose to purge the DB but that did not work. So can you go to the settings and click delete database. Then try it again. If you have this issue again please upload the 0.log like before, Thanks!!

**Comment by mygitaccount420** [comment]
Still crashes. 
[0.log](https://github.com/Nexusoft/nexus-mobile/files/11182238/0.log)
