### ISSUE TITLE
Mobile wallet not seeing balance on a staking Sigchain - 0.9.2-7 Android, Core 5.1.0-rc9

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/nexus-mobile#28]
I just downloaded the 0.9.2.7 version of the Android wallet with the 5.1(9) core.  I am not seeing any balances on my primary Sigchain, which is staking.  The wallet also doesn't recognize my recovery phrase.  Here's the 0.log from the phone. 
 
Another Sigchain which is not staking, balance shows fine.

[Neal-0.log](https://github.com/Nexusoft/nexus-mobile/files/11081303/0.14.log)

**Comment by KenCorma** [comment]
Closing this as we have moved to RC12, open new issue if this persists.
