### ISSUE TITLE
Mobile wallet not working- Crashing, 0.9.2-7 Android, Core 5.1.0-rc9

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/nexus-mobile#29]
Mobile wallet is still not working for me. I have tried everything. Deleting the database several times. Uninstalling and power cycling the phone, everything. 0.9.2-7 Android 13.

That Sigchain is staking and has a recovery phrase setup, so it is as if it is not recognizing anything but the username? I am also using a Samsung S21 Ultra.
![photo_2023-03-27 22 39 34](https://user-images.githubusercontent.com/84140911/228015350-69e967c0-a7fe-475f-a99f-944c31e58eda.jpeg)

I just reinstalled everything from the Android link in Viz.'s Tweet. Now it's much worse. The wallet crashes before getting to 10% synchronized - 3 times. It still says version 0.9.2-7

[Chuck-0.log](https://github.com/Nexusoft/nexus-mobile/files/11081348/0.15.log)

**Comment by KenCorma** [comment]
Closing this as we have moved to RC12, open new issue if this persists.
