### ISSUE TITLE
Mobile wallet crashing while clicking on transactions with a non staking sig-chain. 5.1-rc12

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/nexus-mobile#30]
The Android mobile wallet with core version - 5.1-rc12, crashes when clicking on transactions with a non-staking sigchain.

[Cezarone0.log](https://github.com/Nexusoft/nexus-mobile/files/11133280/0.log)-rc12

**Comment by Aeonwise** [comment]
After deleting the database and logging in again, the failed authentication error pops up, although I am logged in, the balance is correct but it does not display all accounts in 'Accounts', after clicking 'Transactions', you have to wait about 30 seconds and it displays fine, I have an exclamation mark next to set recovery phrase, despite the fact that I have set and there was no exclamation mark before,

**Comment by KenCorma** [comment]
Can I get the revised 0.log, Thanks.

**Comment by KenCorma** [comment]
Merge Issue to #31
