### ISSUE TITLE
(Transaction Issues) Transactions history don't work properly.

### ISSUE THREAD

**Issue by NexusKing83** [Nexusoft/nexus-mobile#31]
Mobile wallet. Android 13 Samsung Galaxy S21 Ultra 5G.
New version 0.9.3 using 5.1.0-rc12 daemon.
Transactions history not working properly. I can't check my transactions before 17th of March. Also February and January this 2023. Also filtering not working i cant check 2022 and 2021 year.
Im staking 3% and this on trust account.
Could you check Kendal this problem...
Thank you

**Comment by KenCorma** [comment]
Is it possible to upload the 0.log? You might have to plug your phone into the computer to see it but it is here:
`Android/data/io.nexus.wallet/Nexus/client/log/0.log`

Thanks!

**Comment by NexusKing83** [comment]
[0.log](https://github.com/Nexusoft/nexus-mobile/files/11153872/0.log)

**Comment by KenCorma** [comment]
Merging all transaction issues here

**Comment by NexusKing83** [comment]
Wrong Balance, show me transactions history from 2021 November 
First i had Balance 0 NXS on mobile network then i came home and on Wifi show me wrong Balance
Version now is 5.1.0-RC14 
0.9.4-4 
Installed and uninstalled 3 times and try to log in few times. 
[0.log](https://github.com/Nexusoft/nexus-mobile/files/11255541/0.log)

**Comment by NealHelman** [comment]
Using 0.9.5-2, I was able to go as far back as Feb 15, 2024, and that was only after I set transaction search to a year.  Before I did that, I could only get as far back as Mar 5, 2024.

**Comment by NealHelman** [comment]
Using 0.9.5-7, I went from Jul 18, 2024 and could get no further than Jun 30, 2024.  After getting back that far, the transactions recycled to Jul 3, 2024.  I kept on trying to get earlier transactions, and the app crashed.
