### ISSUE TITLE
Cannot set recovery phrase

### ISSUE THREAD

**Issue by NealHelman** [Nexusoft/nexus-mobile#34]
v0.9.5-5 Android
Created a new sigchain, and it logged me in.
Immediately went to create a new recovery phrase.
Clicked the "10 words" button to generate a random recovery phrase, clicked Update
Entered the words to confirm.
Got an error indicating Failed to read crypto register.

**Comment by Qrysto** [comment]
@NealHelman I can't reproduce this bug. Have you come back and tried again later?

**Comment by NealHelman** [comment]
@Qrysto Sorry for the delay.  I started the wallet from scratch (not reinstalled, but reran), let it sync, logged in, and lo and behold, it let me set the recovery phrase using the same one I'd attempted last week.
