### ISSUE TITLE
Android 0.9.9-1 crashes at startup

### ISSUE THREAD

**Issue by NealHelman** [Nexusoft/nexus-mobile#36]
Multiple users have reported this.  I use a Samsung Galaxy S24+.  I uninstalled and reinstalled the app, and it doesn't run past the splash screen.

**Comment by NealHelman** [comment]
Attaching a crash log, Android 14.
[nexus-crash.log](https://github.com/user-attachments/files/17365672/nexus-crash.log)

**Comment by KenCorma** [comment]
Has nothing to do with nexus its that in android 14 services need these new declarations 
https://developer.android.com/about/versions/14/changes/fgs-types-required
I will add that and submit a fix soon.
